"""user avatar

Revision ID: 15cde0f76cea
Revises: 67ebb83813ba
Create Date: 2021-11-07 10:25:49.221290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15cde0f76cea'
down_revision = '67ebb83813ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poll', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('avatar', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar')
    op.drop_column('poll', 'timestamp')
    # ### end Alembic commands ###
